### PR TITLE
Issue 12

### PR DESCRIPTION
**Pull request by vitaluha**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2`
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| License                  | CC-BY-SA-4.0

### CODE REVIEW

**Review by vitaluha — COMMENTED** [review]
I created a 'data' file that assigns JSON to a variable. This way it can be read and looped over.

**Comment by MathematicsCLtd** [comment]
Thanks @vitaluha , I'm reviewing. Let me add two more issues and show what I'd like the map to do. Then we can decide the best way to go forward considering all the issues.

**Review by MathematicsCLtd — COMMENTED** [review]
I found a way to use the $.getJSON call. 'Please look at the Add function to wrap getJSON' call Pull Request and the updated hubs.js file.

**Comment by MathematicsCLtd** [comment]
I didn't want to delete this branch yet in case there was something you wanted to copy from it.

**Comment by vitaluha** [comment]
Cool. No problem. You can delete it.

**Pull request closed without merging**
